//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XILabsStudio.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XILabsStudio.Resources.Strings.XIResources", typeof(XIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        internal static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Voice Cloning
        ///Starter+ only.
        ///Clone a voice from a clean sample recording. Samples should contain 1 speaker and be over 1 minute long and not contain background noise..
        /// </summary>
        internal static string AddVoicePopup_InstantVoiceCloningDescription {
            get {
                return ResourceManager.GetString("AddVoicePopup.InstantVoiceCloningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Voice Cloning
        ///Creator+ only.
        ///Create a perfect digital replica of your voice..
        /// </summary>
        internal static string AddVoicePopup_ProfessionalVoiceCloningDescription {
            get {
                return ResourceManager.GetString("AddVoicePopup.ProfessionalVoiceCloningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of voice to create.
        /// </summary>
        internal static string AddVoicePopup_TypeOfVoiceToCreate {
            get {
                return ResourceManager.GetString("AddVoicePopup.TypeOfVoiceToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Design
        ///Design entirely new voices by adjusting their parameters. Every voice you create is randomly generated and is entirely unique even if the same settings are applied..
        /// </summary>
        internal static string AddVoicePopup_VoiceDesignDescription {
            get {
                return ResourceManager.GetString("AddVoicePopup.VoiceDesignDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice LibraryAdd a voice from our community..
        /// </summary>
        internal static string AddVoicePopup_VoiceLibraryDescription {
            get {
                return ResourceManager.GetString("AddVoicePopup.VoiceLibraryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Audio.
        /// </summary>
        internal static string AudioPlayerPopup_DownloadAudio {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.DownloadAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to choose a folder to continue downloading your audio file..
        /// </summary>
        internal static string AudioPlayerPopup_DownloadAudio_ChooseAFolderMessage {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.DownloadAudio.ChooseAFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a folder to download audio:.
        /// </summary>
        internal static string AudioPlayerPopup_DownloadAudio_ChooseAFolderTitle {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.DownloadAudio.ChooseAFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter file name.
        /// </summary>
        internal static string AudioPlayerPopup_DownloadAudio_EnterFileName {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.DownloadAudio.EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved!.
        /// </summary>
        internal static string AudioPlayerPopup_DownloadAudio_FileSaved {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.DownloadAudio.FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast-forward 10 seconds.
        /// </summary>
        internal static string AudioPlayerPopup_FastForward {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.FastForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize Audio Player.
        /// </summary>
        internal static string AudioPlayerPopup_MaximizeAudioPlayer {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.MaximizeAudioPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize Audio Player.
        /// </summary>
        internal static string AudioPlayerPopup_MinimizeAudioPlayer {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.MinimizeAudioPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        internal static string AudioPlayerPopup_PlayPause {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind 10 seconds.
        /// </summary>
        internal static string AudioPlayerPopup_Rewind {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.Rewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Audio.
        /// </summary>
        internal static string AudioPlayerPopup_ShareAudio {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.ShareAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbs down.
        /// </summary>
        internal static string AudioPlayerPopup_ThumbsDown {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.ThumbsDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbs up.
        /// </summary>
        internal static string AudioPlayerPopup_ThumbsUp {
            get {
                return ResourceManager.GetString("AudioPlayerPopup.ThumbsUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a model to use.
        /// </summary>
        internal static string ChooseAModelPopup_ChooseAModel {
            get {
                return ResourceManager.GetString("ChooseAModelPopup.ChooseAModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to your clipboard.
        /// </summary>
        internal static string CopiedToYourClipboard {
            get {
                return ResourceManager.GetString("CopiedToYourClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Voice.
        /// </summary>
        internal static string EditVoice {
            get {
                return ResourceManager.GetString("EditVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XI-API-Key: .
        /// </summary>
        internal static string FirstRunXP_APIKeyEntryPlaceholder {
            get {
                return ResourceManager.GetString("FirstRunXP.APIKeyEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string FirstRunXP_ConnectButton {
            get {
                return ResourceManager.GetString("FirstRunXP.ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue, you need to provide your ElevenLabs API key..
        /// </summary>
        internal static string FirstRunXP_EmptyAPIKeyAlertDescription {
            get {
                return ResourceManager.GetString("FirstRunXP.EmptyAPIKeyAlertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An API key is required.
        /// </summary>
        internal static string FirstRunXP_EmptyAPIKeyAlertTitle {
            get {
                return ResourceManager.GetString("FirstRunXP.EmptyAPIKeyAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string FirstRunXP_RememberMeLabel {
            get {
                return ResourceManager.GetString("FirstRunXP.RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-run Experience.
        /// </summary>
        internal static string FirstRunXP_Title {
            get {
                return ResourceManager.GetString("FirstRunXP.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to XILabs&apos; unofficial studio – your gateway to a groundbreaking multiplatform app for creating and leveraging AI-voiced content. Whether you&apos;re a developer, artist, or creator, we&apos;re thrilled to have you join our vibrant community.
        ///To get started, you have to enter your ElevenLabs API key.
        ///You can view your xi-api-key using the &apos;Profile&apos; tab on the website. https://elevenlabs.io.
        ///Remember, this project is open source – we encourage you to participate in its development!
        ///Additionally, if you enco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstRunXP_WelcomeMessage {
            get {
                return ResourceManager.GetString("FirstRunXP.WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong ElevenLabs API key. Please check your API key at .
        /// </summary>
        internal static string FirstRunXP_WrongAPIKeyAlertDescription {
            get {
                return ResourceManager.GetString("FirstRunXP.WrongAPIKeyAlertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong API Key.
        /// </summary>
        internal static string FirstRunXP_WrongAPIKeyAlertTitle {
            get {
                return ResourceManager.GetString("FirstRunXP.WrongAPIKeyAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string HistoryPage_DeleteSelectedItemsAlert_Delete {
            get {
                return ResourceManager.GetString("HistoryPage.DeleteSelectedItemsAlert.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected history items? This actions cannot be undone..
        /// </summary>
        internal static string HistoryPage_DeleteSelectedItemsAlertDescription {
            get {
                return ResourceManager.GetString("HistoryPage.DeleteSelectedItemsAlertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete History Items.
        /// </summary>
        internal static string HistoryPage_DeleteSelectedItemsAlertTitle {
            get {
                return ResourceManager.GetString("HistoryPage.DeleteSelectedItemsAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full list of all your generated samples, ready for download..
        /// </summary>
        internal static string HistoryPage_Description {
            get {
                return ResourceManager.GetString("HistoryPage.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Selected.
        /// </summary>
        internal static string HistoryPage_DownloadSelected {
            get {
                return ResourceManager.GetString("HistoryPage.DownloadSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        internal static string HistoryPage_RemoveSelected {
            get {
                return ResourceManager.GetString("HistoryPage.RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to allow the following permission(s) to continue..
        /// </summary>
        internal static string OnAndroid_AskForPermissionMessage {
            get {
                return ResourceManager.GetString("OnAndroid.AskForPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow app permission.
        /// </summary>
        internal static string OnAndroid_AskForPermissionTitle {
            get {
                return ResourceManager.GetString("OnAndroid.AskForPermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item..
        /// </summary>
        internal static string SelectAnItem {
            get {
                return ResourceManager.GetString("SelectAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing.
        /// </summary>
        internal static string Sharing {
            get {
                return ResourceManager.GetString("Sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubbing.
        /// </summary>
        internal static string Shell_DubbingTabTitle {
            get {
                return ResourceManager.GetString("Shell.DubbingTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically voice your content into other languages.
        /// </summary>
        internal static string Shell_DubbingTabTooltip {
            get {
                return ResourceManager.GetString("Shell.DubbingTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string Shell_HistoryTabTitle {
            get {
                return ResourceManager.GetString("Shell.HistoryTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Shell_ProjectsTabTitle {
            get {
                return ResourceManager.GetString("Shell.ProjectsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our advanced long-form Speech Synthesis editor.
        /// </summary>
        internal static string Shell_projectsTabTooltip {
            get {
                return ResourceManager.GetString("Shell.projectsTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Synthesis.
        /// </summary>
        internal static string Shell_SpeechSynthesisTabTitle {
            get {
                return ResourceManager.GetString("Shell.SpeechSynthesisTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate impeccable speech.
        /// </summary>
        internal static string Shell_SpeechSynthesisTabTooltip {
            get {
                return ResourceManager.GetString("Shell.SpeechSynthesisTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceLab.
        /// </summary>
        internal static string Shell_VoiceLabTabTitle {
            get {
                return ResourceManager.GetString("Shell.VoiceLabTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Voice Design and Instant Voice Cloning.
        /// </summary>
        internal static string Shell_VoiceLabTabTooltip {
            get {
                return ResourceManager.GetString("Shell.VoiceLabTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Library.
        /// </summary>
        internal static string Shell_VoiceLibraryTabTitle {
            get {
                return ResourceManager.GetString("Shell.VoiceLibraryTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore shared voices from the community.
        /// </summary>
        internal static string Shell_VoiceLibraryTabTooltip {
            get {
                return ResourceManager.GetString("Shell.VoiceLibraryTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add voice.
        /// </summary>
        internal static string SpeechSynthesisPage_AddVoice {
            get {
                return ResourceManager.GetString("SpeechSynthesisPage.AddVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unleash the power of our cutting-edge technology to generate realistic, captivating speech in a wide range of languages..
        /// </summary>
        internal static string SpeechSynthesisPage_Description {
            get {
                return ResourceManager.GetString("SpeechSynthesisPage.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string SpeechSynthesisPage_Generate {
            get {
                return ResourceManager.GetString("SpeechSynthesisPage.Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SpeechSynthesisPage_Settings {
            get {
                return ResourceManager.GetString("SpeechSynthesisPage.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total quota remaining.
        /// </summary>
        internal static string SpeechSynthesisPage_TotalRemainingQuota {
            get {
                return ResourceManager.GetString("SpeechSynthesisPage.TotalRemainingQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or paste text here. The model works best on longer fragments..
        /// </summary>
        internal static string SpeechSynthesisPage_TTSInput {
            get {
                return ResourceManager.GetString("SpeechSynthesisPage.TTSInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice: .
        /// </summary>
        internal static string SpeechSynthesisPage_Voice {
            get {
                return ResourceManager.GetString("SpeechSynthesisPage.Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Settings.
        /// </summary>
        internal static string SpeechSynthesisPage_VoiceSettings {
            get {
                return ResourceManager.GetString("SpeechSynthesisPage.VoiceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Analytics.
        /// </summary>
        internal static string UsageAnalytics {
            get {
                return ResourceManager.GetString("UsageAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Strength.
        /// </summary>
        internal static string VoiceDesignPopup_AccentStrength {
            get {
                return ResourceManager.GetString("VoiceDesignPopup.AccentStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First we thought the PC was a calculator. Then we found out how to turn numbers into letters and we thought it was a typewriter..
        /// </summary>
        internal static string VoiceDesignPopup_DefaultText {
            get {
                return ResourceManager.GetString("VoiceDesignPopup.DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Voice.
        /// </summary>
        internal static string VoiceDesignPopup_GenerateVoice {
            get {
                return ResourceManager.GetString("VoiceDesignPopup.GenerateVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Voice.
        /// </summary>
        internal static string VoiceDesignPopup_UseVoice {
            get {
                return ResourceManager.GetString("VoiceDesignPopup.UseVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you describe the voice? e.g., &quot;an old American male voice with a slight hoarseness in his throat. Perfect for news.&quot;.
        /// </summary>
        internal static string VoiceDetailsPopup_HowWouldYouDescribeTheVoice {
            get {
                return ResourceManager.GetString("VoiceDetailsPopup.HowWouldYouDescribeTheVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Generative or Cloned Voice.
        /// </summary>
        internal static string VoiceLabPage_AddGenerativeOrClonedVoice {
            get {
                return ResourceManager.GetString("VoiceLabPage.AddGenerativeOrClonedVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your creative AI toolkit. Design entirely new synthetic voices from scratch. Clone your own voice or a voice you have a permission and rights to. Only you have access to the voices you create..
        /// </summary>
        internal static string VoiceLabPage_Description {
            get {
                return ResourceManager.GetString("VoiceLabPage.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarity + Similarity Enhancement.
        /// </summary>
        internal static string VoiceSettingsPopup_ClarityPlusSimilarityEnhancement {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.ClarityPlusSimilarityEnhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exaggerated.
        /// </summary>
        internal static string VoiceSettingsPopup_Exaggerated {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.Exaggerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string VoiceSettingsPopup_High {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string VoiceSettingsPopup_Low {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More stable.
        /// </summary>
        internal static string VoiceSettingsPopup_MoreStable {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.MoreStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More variable.
        /// </summary>
        internal static string VoiceSettingsPopup_MoreVariable {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.MoreVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None (Fastest).
        /// </summary>
        internal static string VoiceSettingsPopup_None {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Boost.
        /// </summary>
        internal static string VoiceSettingsPopup_SpeakerBoost {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.SpeakerBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stability.
        /// </summary>
        internal static string VoiceSettingsPopup_Stability {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.Stability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Exaggeration.
        /// </summary>
        internal static string VoiceSettingsPopup_StyleExaggeration {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.StyleExaggeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Default.
        /// </summary>
        internal static string VoiceSettingsPopup_ToDefault {
            get {
                return ResourceManager.GetString("VoiceSettingsPopup.ToDefault", resourceCulture);
            }
        }
    }
}
